### ISSUE TITLE
ModuleNotFoundError: No module named 'map_ops'

### ISSUE THREAD

**Issue by eastrocky** [kremrik/coercion#4]
**Dockerfile**
```Dockerfile
ARG VARIANT="3.8"
FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}
```

**requirements.txt**
```
git+https://github.com/kremrik/coercion.git

```

**Install**
```shell
pip3 install --user -r requirements.txt
```

When I attempt to run your examples:
```python
from coercion import coerce

# schemas are just dictionaries, with the types specified
# as regular python `type`s:
schema = {"foo": int, "bar": float}
record = {"foo": "1", "baz": "remove-me"}

print(coerce(schema, record))
```

```shell
vscode ➜ /workspaces/someApp (master ✗) $ /usr/local/bin/python /workspaces/someApp/main.py
Traceback (most recent call last):
  File "/workspaces/someApp/main.py", line 1, in <module>
    from coercion import coerce
  File "/home/vscode/.local/lib/python3.8/site-packages/coercion/__init__.py", line 1, in <module>
    from coercion.coercion import coerce
  File "/home/vscode/.local/lib/python3.8/site-packages/coercion/coercion.py", line 1, in <module>
    from map_ops.core import cut_, diff_, put_
ModuleNotFoundError: No module named 'map_ops'
```

**Comment by kremrik** [comment]
@eastrocky v0.1.1 created, let me know if that fixes it! Was able to install both by cloning and running `pip install .` and `python -m pip install git+https://github.com/kremrik/coercion.git`

**Comment by eastrocky** [comment]
It works!
